### ISSUE TITLE
Wire up changelog / version management with Expeditor

### ISSUE THREAD

**Issue by tas50** [chef/vscode-chef#105]
Phase 1 of release automation for this repository is to wire up Expeditor to handle the version bumps and the changelog generation.

**Comment by marcparadise** [comment]
###  Getting Started

Background: currently when we merge a change to this repository, we need to manually update the changelog and update versions.  Expeditor is the tool we use across our Chef projects that automate those kinds of tasks (and many more!) 

You can find documentation about the expeditor system at https://expeditor.chef.io/docs/getting-started/.  If you haven't already read that, the remainder of what I've written below will probably make more sense after doing so. 

Most of our repositories have examples of expeditor configurations. This is a good one to start with, as it's similar to what we'll need here: 

https://github.com/chef/chef-apply/blob/master/.expeditor/config.yml

That expeditor configuration will trigger a changelog update and version update with every merge to master. 
 
The differences in config that we'll need here: 
-  this is not a rubygem - so the final step under `promote -> actions' to `built_in:publish_rubygems` should not be there. 
- We also don't have verification tests for this repository; therefore we would not use a verification pipeline, and so you can omit the `pipelines` section of the config for now. 
- https://github.com/chef/chef-apply/blob/master/.expeditor/config.yml#L33 - that references the script  that gets run every time a new version is created (eg when changes are merged to master).   In the chef-apply repository, that script (https://github.com/chef/chef-apply/blob/master/.expeditor/update_version.sh) updates a ruby file. You'll need a version of that same script for this repository, but it will need to update the version in `package.json` instead. 

We can take a look once you get to that point.

**Comment by marcparadise** [comment]
Complete with https://github.com/chef/vscode-chef/pull/108
