### ISSUE TITLE
Globally suppress individual rules

### ISSUE THREAD

**Issue by mikemol** [chef/vscode-chef#23]
The VSCode extension allows you to specify a path to a foodcritic binary, but doesn't appear to let you specify any custom command-line arguments. That would be a helpful feature.

For one reason or another (i.e. a cookbook isn't meant for publication outside an organization), some rules like FC078 aren't helpful. Foodcritic allows you to specify, e.g. `-FC078` on the command line, to suppress inappropriate rules.

Foodcritic does allow you to use comments to ignore rules within files in a targeted fashion, but that doesn't help if the rule (such as FC071) is about not having a file in the first place!

**Comment by stuartpreston** [comment]
Thanks for the suggestion, yes we should try and support some sort of argument customization from the command line.  Though I know we at Chef are making some improvements to that area so I'll try and find out what they are and report back.

**Comment by stuartpreston** [comment]
@tas50 Do you know any alternatives to applying the foodcritic ignores at the command line?

**Comment by sll552** [comment]
Hi,
this would be a very welcome addition.

It is possible to create a `.foodcritic` file (e.g. at repo level) where all disabled rules are listed. For foodcritic to read the file the `-r filename` parameter is requiered. For example we run foodcritic in the root dir of our repo with `foodcritic -r .foodcritic`. See http://www.foodcritic.io/#choosing-rules-to-run for more info.

Maybe you could add an option for a .foodcritic file the same way as there already is one for rubocop (rubocop.configFile)

**Comment by stuartpreston** [comment]
@sll552 That's a great idea.  In fact I just tested and it looks like the `-r .foodcritic` can be specified and will be ignored if the file does not exist.  So how about I add a foodcritic config path that defaults to `.foodcritic` - that way it can be overridden to a specific path inside the repo, or it will use the one at the root by default...  Thoughts?

**Comment by stuartpreston** [comment]
Ah, no it's not ignored - I just put the argument in the wrong place.  But implementation wise I think we can do something here.

**Comment by stuartpreston** [comment]
We no longer use Foodcritic at all in the extension so instead you should be able to configure Cookstyle for this. Closing this issue for now.
