### ISSUE TITLE
Don't Lint Entire Repo When Repo is Large

### ISSUE THREAD

**Issue by benmontour-wf** [chef/vscode-chef#33]
I'm curious if there is a way to prevent this extension from linting the entire repo everytime a file gets saved. I have a rather large Chef repo and it's about 30 seconds on every save before this comes back with linter errors to fix because it has to run on the whole repo every time. I'd like it to lint the currently open file only if possible like most other linters do. Is there a config setting I can flip to enable that or disable the whole repo linting feature?

**Comment by stuartpreston** [comment]
Hi @benmontour-wf sorry for the delay in responding. There isn't a way today to prevent the extension from linting the entire repo.  I can take reponsibility for that choice -- it was to avoid a situation where you are working with one file, save it, fix the rubocop errors and then assume you are done.  If I get some time I will try and take a look at that option in future unless someone else wants to jump in and fix it, providing an option like you ask for. I hope you found the setting (rubocop.enable) that disables the whole linting feature.

**Comment by benmontour-wf** [comment]
No problem at all on the delay, I appreciate you responding.
Yeah I found the disable all linting, I was just hoping for a way to limit it in scope, because of the size of our Chef repo and how many linting errors it finds (as we didn't have Rubocop/Cookstyle linting when we started it). I look forward to the future setting if it ends up happening. Thanks again for a great product!

**Comment by benmontour-wf** [comment]
- Issue Type: `Performance`
- Extension Name: `chef`
- Extension Version: `0.7.1`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.1`

This is still a large issue. Now the latest versions of VSCode are flagging this extension as causing CPU performance issues and becoming unresponsive. This is due to this extension linting the entire repo at once instead of just the file or folder that is open. I'd use just the normal Ruby extension for linting but run into large issues with it supporting CookStyle/FoodCritic instead of standard Rubocop. We have a large Chef repo with dozens of cookbooks and hundreds of Ruby files. This extension is completely unusable right now because saving changes to any recipe causes VSCode to hang for minutes at a time.
[Pendrica.chef-unresponsive.cpuprofile.txt](https://github.com/pendrica/vscode-chef/files/3632041/Pendrica.chef-unresponsive.cpuprofile.txt)

**Comment by clintoncwolfe** [comment]
I'm implemeting the following proposed fix:
* Modify the linter routine to take a list of paths.
* At startup (and possibly at workspace change), count the number of .rb files in the workspace. If the count is more than a configurable threshold, issue a dismissable warning, and only lint the files that are open in editors.
* Expose a Command that allows you to lint the entire workspace regardless of size.
