### ISSUE TITLE
registry_key needs a more compact autofill

### ISSUE THREAD

**Issue by sam1el** [chef/vscode-chef#48]
# Describe the problem
At my current customer, we had a recipe with around 80 registry_key resources. The recipes itself with guards and the way vscode-chef currently auto populates the resource, the recipe itself was nearing 1300 lines of code. I believe a more compact method would not only make the code cleaner but, easier to understand and more compact. It also seems that the current layout gives me a few cookstyle errors. 

## Software Version
vscode-chef 0.8.1

## Replication Case

```#! /bin/ruby
registry_key 'HKEY_LOCAL_MACHINE\\...\\System' do
  values [{
    name: 'NewRegistryKeyValue',
    type: :multi_string,
    data: %w(foo bar baz),
  }]
  action :create
end
```

## Possible Solution

A layout more like this would drastically reduce clutter

```#! /bin/ruby
registry_key 'HKEY_LOCAL_MACHINE\\...\\System' do
  values [{ name: 'NewRegistryKeyValue', type: :multi_string, data: %w(foo bar baz) }]
  action :create
end
```

**Comment by tas50** [comment]
Closing this as a wont-fix.
