### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by oleksandrnezhynskyi** [chef/vscode-chef#72]
[chef-software.chef-unresponsive.cpuprofile.txt](https://github.com/chef/vscode-chef/files/4218366/chef-software.chef-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `chef`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.42.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by meowtochondria** [comment]
Same on Ubuntu 18.04.4 LTS with VSCode 1.43.2.

**Comment by clintoncwolfe** [comment]
From the profiler data, 99.39% of time was spent in this line, https://github.com/chef/vscode-chef/blob/6bbf4778e48efc11ca52ef318b3b967ad631dbca/extension.ts#L64, which is the subprocess spawn to run rubocop.

**Comment by clintoncwolfe** [comment]
I believe this an example of #33, running the linter on a large repo.
