### ISSUE TITLE
Cannot activate the extension because it depends on an unknown 'ebornix.ruby' extension

### ISSUE THREAD

**Issue by jakauppila** [chef/vscode-chef#87]
# Describe the problem
I have installed the extension, but am getting the following error when VSCode attempts to activate it:

![image](https://user-images.githubusercontent.com/4100127/83278904-eb6bcc00-a199-11ea-94b8-cfa4eac839fe.png)

## Software Version
Chef Infra Extension for Visual Studio Code v1.6.1
VSCode 1.45.1
Windows 10 1909

## Possible Solution
I'm guessing this is a typo and the dependency should instead be `rebornix.ruby` ?

**Comment by clintoncwolfe** [comment]
This appears to have been fixed in 61b0182 / v1.6.2

**Comment by tas50** [comment]
Yep I pushed the fix for this one. Sorry about that @jakauppila.
